#include "nonClassFunctions.h"

void AddDistricts(QComboBox *DT){
    DT->addItem("Abbottabad");
    DT->addItem("Astore");
    DT->addItem("Attock");
    DT->addItem("Awaran");
    DT->addItem("Badin");
    DT->addItem("Bagh");
    DT->addItem("Bahawalnagar");
    DT->addItem("Bahawalpur");
    DT->addItem("Bajaur");
    DT->addItem("Bannu");
    DT->addItem("Barkhan");
    DT->addItem("Batagram");
    DT->addItem("Bhakkar");
    DT->addItem("Bhimber");
    DT->addItem("Buner");
    DT->addItem("Chagai");
    DT->addItem("Chakwal");
    DT->addItem("Charsadda");
    DT->addItem("Chiniot");
    DT->addItem("Dadu");
    DT->addItem("Darel");
    DT->addItem("Dera Bugti");
    DT->addItem("Dera Ghazi Khan");
    DT->addItem("Dera Ismail Khan");
    DT->addItem("Diamer");
    DT->addItem("Duki");
    DT->addItem("Faisalabad");
    DT->addItem("Ghanche");
    DT->addItem("Ghizer");
    DT->addItem("Ghotki");
    DT->addItem("Gilgit");
    DT->addItem("Gujranwala");
    DT->addItem("Gujrat");
    DT->addItem("Gupis Yasin");
    DT->addItem("Gwadar");
    DT->addItem("Hafizabad");
    DT->addItem("Hangu");
    DT->addItem("Haripur");
    DT->addItem("Harnai");
    DT->addItem("Hattian");
    DT->addItem("Haveli");
    DT->addItem("Hunza");
    DT->addItem("Hyderabad");
    DT->addItem("Islamabad");
    DT->addItem("Jacobabad");
    DT->addItem("Jafarabad");
    DT->addItem("Jamshoro");
    DT->addItem("Jhal Magsi");
    DT->addItem("Jhang");
    DT->addItem("Jhelum");
    DT->addItem("Kachhi");
    DT->addItem("Kalat");
    DT->addItem("Karachi Central");
    DT->addItem("Karachi East");
    DT->addItem("Karachi South");
    DT->addItem("Karachi West");
    DT->addItem("Karak");
    DT->addItem("Kashmore ");
    DT->addItem("Kasur");
    DT->addItem("Kech");
    DT->addItem("Khairpur");
    DT->addItem("Khanewal");
    DT->addItem("Kharan");
    DT->addItem("Kharmang");
    DT->addItem("Khushab");
    DT->addItem("Khuzdar");
    DT->addItem("Khyber");
    DT->addItem("Killa Abdullah");
    DT->addItem("Kohat");
    DT->addItem("Kohlu");
    DT->addItem("Kolai Pallas");
    DT->addItem("Korangi");
    DT->addItem("Kotli");
    DT->addItem("Kurram");
    DT->addItem("Lahore");
    DT->addItem("Lakki Marwat");
    DT->addItem("Larkana");
    DT->addItem("Lasbela");
    DT->addItem("Layyah");
    DT->addItem("Lodhran");
    DT->addItem("Loralai");
    DT->addItem("Lower Chitral");
    DT->addItem("Lower Dir");
    DT->addItem("Lower Kohistan");
    DT->addItem("Malakand");
    DT->addItem("Malir");
    DT->addItem("Mandi Bahauddin");
    DT->addItem("Mansehra");
    DT->addItem("Mardan");
    DT->addItem("Mastung");
    DT->addItem("Matiari");
    DT->addItem("Mianwali");
    DT->addItem("Mirpur Khas");
    DT->addItem("Mirpur");
    DT->addItem("Mohmand");
    DT->addItem("Multan");
    DT->addItem("Musakhel");
    DT->addItem("Muzaffarabad");
    DT->addItem("Muzaffargarh");
    DT->addItem("Nagar");
    DT->addItem("Nankana Sahib");
    DT->addItem("Narowal");
    DT->addItem("Naseerabad");
    DT->addItem("Naushahro Firoze");
    DT->addItem("Neelum");
    DT->addItem("North Waziristan");
    DT->addItem("Nowshera");
    DT->addItem("Nushki");
    DT->addItem("Okara");
    DT->addItem("Orakzai");
    DT->addItem("Pakpattan");
    DT->addItem("Panjgur");
    DT->addItem("Peshawar");
    DT->addItem("Pishin");
    DT->addItem("Poonch");
    DT->addItem("Qambar Shahdadkot");
    DT->addItem("Qilla Saifullah");
    DT->addItem("Quetta");
    DT->addItem("Rahim Yar Khan");
    DT->addItem("Rajanpur");
    DT->addItem("Rawalpindi");
    DT->addItem("Roundu");
    DT->addItem("Sahiwal");
    DT->addItem("Sanghar");
    DT->addItem("Sargodha");
    DT->addItem("Shaheed Benazirabad");
    DT->addItem("Shaheed Sikandarabad");
    DT->addItem("Shangla");
    DT->addItem("Sheikhupura");
    DT->addItem("Sherani");
    DT->addItem("Shigar");
    DT->addItem("Shikarpur");
    DT->addItem("Sialkot");
    DT->addItem("Sibi");
    DT->addItem("Skardu");
    DT->addItem("Sohbatpur");
    DT->addItem("South Waziristan");
    DT->addItem("Sudhnutti");
    DT->addItem("Sujawal");
    DT->addItem("Sukkur");
    DT->addItem("Swabi");
    DT->addItem("Swat");
    DT->addItem("Tando Allahyar");
    DT->addItem("Tando Muhammad Khan");
    DT->addItem("Tangir");
    DT->addItem("Tank");
    DT->addItem("Tharparkar");
    DT->addItem("Thatta");
    DT->addItem("Toba Tek Singh");
    DT->addItem("Tor Ghar");
    DT->addItem("Umerkot");
    DT->addItem("Upper Chitral");
    DT->addItem("Upper Dir");
    DT->addItem("Upper Kohistan");
    DT->addItem("Vehari");
    DT->addItem("Washuk");
    DT->addItem("Zhob");
    DT->addItem("Ziarat");
}

void AddInitialDate(QComboBox *Day, QComboBox *Month, QComboBox *Year)
{
    for(int i = 1; i < 32 ;i++){
        Day->addItem(QString::number(i));
    }

    Month->addItem("January");
    Month->addItem("February");
    Month->addItem("March");
    Month->addItem("April");
    Month->addItem("May");
    Month->addItem("June");
    Month->addItem("July");
    Month->addItem("August");
    Month->addItem("September");
    Month->addItem("October");
    Month->addItem("November");
    Month->addItem("December");

    for(int i = 2008; i > 1990; i--){
        Year->addItem(QString::number(i));
    }
}

void InitializeQLabels(QLabel *AIT[])
{
    AIT[0]->setText("CMS ID     ");
    AIT[1]->setText("USER NAME   ");
    AIT[2]->setText("PASSWORD     ");
    AIT[3]->setText("NAME         ");
    AIT[4]->setText("DATE OF BIRTH  ");
    AIT[5]->setText("ROOM NUMBER   ");
    AIT[6]->setText("CONTACT #   ");
    AIT[7]->setText("ADDRESS  ");
    AIT[8]->setText("CNIC        ");
    AIT[9]->setText("GUARDIAN NAME");
    AIT[10]->setText("GUARDIAN PHONE #");
}
